<a href="https://colab.research.google.com/github/glorykim999910/aiacademy/blob/master/3%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C(%EA%B9%80%EC%83%81%EB%AF%BC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3주차 과제
- 학습률 최적화
- 군집 분석(병합 계층 군집) 구현 클론 코딩
- Cost function 구현

## 1. 학습률 최적화

간단한 예제를 통해 학습률 최적화의 중요성에 대해서 확인 해 보도록 하겠습니다.

아래 링크에서 __1단계만__에 손실 곡선의 최저점에 도달하게 하는 학습률을 찾아 정답을 적어주세요

링크: https://developers.google.com/machine-learning/crash-course/fitter/graph?hl=ko

### 정답 : 1.60

## 2. 군집 분석(병합 계층 군집) 구현 클론 코딩

군집 분석 강의(군집문제[2] 3:10 ~ 5:20 부분)를 보고 코드를 따라 치며 출력 결과(과제 설명 페이지 참고)를 만드세요. 

강의에서는 데이터 시각화까지 진행하지만 
과제에서는 표를 출력하는 것 까지만 하시면 됩니다.

3주차 과제 안내 페이지를 보시면 표에 대한 이미지가 있습니다. 참고해주세요

* 병합 계층 군집 동작방식순서
1. 모든 데이터의 거리행렬을 계산
2. 모든 데이터 포인트를 단일 클러스터로 표현
3. 가장 비슷하지 않는, 즉 멀리 떨어진 데이터간의 거리가 기초하여 가장 가까운 두 클러스터를 하나로 합침
4. 유사도 행렬 업데이트
5. 하나의 클러스터가 남을 때까지 2~4단계 반복


In [21]:

import numpy as np # numpy 라이브러리 임포트, 알리아스 : np
np.random.seed(123) # 무작위 랜덤값 시드설정
X = np.random.random_sample([5,3])*10 # 5x3 numpy array에 무작위 랜덤값을 부여하되, 값들사이의 거리값 *10을 부여이후 변수 X에 대입

X # x출력




array([[6.96469186, 2.86139335, 2.26851454],
       [5.51314769, 7.1946897 , 4.2310646 ],
       [9.80764198, 6.84829739, 4.80931901],
       [3.92117518, 3.43178016, 7.29049707],
       [4.38572245, 0.59677897, 3.98044255]])

In [23]:

import pandas as pd # pandas 라이브러리 임포트, 알리아스 : pd
variables = ['X','Y','Z'] # 리스트 ['X', 'Y', 'Z'] 생성 후, 변수 variables에 대입
labels = ['ID_0', 'ID_1', 'ID_2', 'ID_3', 'ID_4'] # 리스트 ['ID_0', 'ID_1', 'ID_2', 'ID_3', 'ID_4'] 생성 후, 변수 labels에 대입  
df = pd.DataFrame(X, columns = variables, index = labels) # DataFrame생성 X는 변수값전체, colums은 variables, index는 labels로 설정이후 변수 df에 대입
df # df 출력



X         Y         Z
ID_0  6.964692  2.861393  2.268515
ID_1  5.513148  7.194690  4.231065
ID_2  9.807642  6.848297  4.809319
ID_3  3.921175  3.431780  7.290497
ID_4  4.385722  0.596779  3.980443

In [33]:
from scipy.spatial.distance import pdist,squareform # scipy.spatial.distance의 pdist, squareform 라이브러리 임포트

Y = pdist(df) # df <-  X,Y,Z 간 거리값을 계산이후 변수 Y에 대입
Y # Y 출력



array([4.973534  , 5.51665266, 5.89988504, 3.83539555, 4.34707339,
       5.10431109, 6.69823298, 7.24426159, 8.31659367, 4.382864  ])

In [34]:
row_dist = pd.DataFrame(squareform(pdist(df, metric='euclidean')), 
                        columns = labels, index=labels) 
# 변수 df를 유클리디언 거리함수로 계산하고, columns과 index를 labels로 설정한 뒤 행렬형식으로 변경하고. 데이터프레임으로 생성한 뒤, 변수 row_dist에 대입 
row_dist # row_dist 출력 

ID_0      ID_1      ID_2      ID_3      ID_4
ID_0  0.000000  4.973534  5.516653  5.899885  3.835396
ID_1  4.973534  0.000000  4.347073  5.104311  6.698233
ID_2  5.516653  4.347073  0.000000  7.244262  8.316594
ID_3  5.899885  5.104311  7.244262  0.000000  4.382864
ID_4  3.835396  6.698233  8.316594  4.382864  0.000000

In [25]:
from scipy.cluster.hierarchy import linkage # scipy.cluster.hierarchy의 linkage 라이브러리 임포트

row_clusters = linkage(row_dist, method = 'complete', metric = 'euclidean') 
# 변수 row_dist의 연결행렬을 complete, 유클리디언 거리함수로 계산후 변수 row_cluster 대입

row_clusters # row_cluster 출력

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 0.        ,  4.        ,  6.52197264,  2.        ],
       [ 1.        ,  2.        ,  6.72960262,  2.        ],
       [ 3.        ,  5.        ,  8.53924727,  3.        ],
       [ 6.        ,  7.        , 12.44482356,  5.        ]])

In [0]:
help(linkage)

In [26]:
row_clusters = linkage(df.values, method = 'complete', metric='euclidean')
# or df의 값에 대한 연결행렬을 complete, 유클리디언 거리함수로 계산 후 변수 row_clusters에 대입
row_clusters # row_clusters 출력

array([[0.        , 4.        , 3.83539555, 2.        ],
       [1.        , 2.        , 4.34707339, 2.        ],
       [3.        , 5.        , 5.89988504, 3.        ],
       [6.        , 7.        , 8.31659367, 5.        ]])

In [27]:
pd.DataFrame(row_clusters, columns = ['row label 1', 'row label 2', 'distance', 'no. of items in clust'], 
             index = ['cluster %d' %(i+1) for i in range(row_clusters.shape[0])])
# row_clusters를 데이터프레임의 값으로 설정하고, columns를 columns = ['row label 1', 'row label 2', 'distance', 'no. of items in clust'], index를 cluster1, cluster2, cluster3, cluster4로 설정


row label 1  row label 2  distance  no. of items in clust
cluster 1          0.0          4.0  3.835396                    2.0
cluster 2          1.0          2.0  4.347073                    2.0
cluster 3          3.0          5.0  5.899885                    3.0
cluster 4          6.0          7.0  8.316594                    5.0

## 3. Cost function 구현
## $$cost(W) =  \frac{1}{n}\sum_{i=1}^n (Wx^{(i)}-y^{(i)})^2$$

### 데이터(X, Y)

In [0]:
# 제공된 데이터는 변경 할 수 없습니다.(문제 & 라벨 데이터)
x = [1, 2, 3]
y = [2, 4, 6]

In [0]:
# 함수테스트
x = [1,2]
y = [3,6]

### cost function을 파이썬으로 구현하세요.
pass를 지우고 cost_func 함수를 완성하세요.

가중치(Weight)를 입력하면 코스트(cost)를 계산하는 함수를 만드는게 목적입니다.

In [103]:
# W(가중치) 데이터 타입 -> int or float
# x(학습 데이터) 데이터 타입 -> list
# y(정답 데이터) 데이터 타입 -> list
# cost_func 함수 리턴값 타입 -> float
# cost_func 함수 리턴값 = cost 값
# W:가중치, x:학습 데이터 y:정답 데이터


W = str(input("가중치를 입력하세요 : "))  

if W.count('.') == 1: # 가중치가 실수일때(String 타입의 w에서 .의 개수 count결과가 1개일때 실수) 
    W = float(W)
else : # 가중치가 정수일때(String 타입의 w에서 .의 개수 count결과가 1개가 아닐때 정수)
    W = int(W)

def cost_func(W, x, y): # 비용함수 정의
  errorbyerror = 0 # (예측값 - 실제값)^2을 0으로 초기화
  for i in range(len(x)): # list x의 길이만큼 반복
    errorbyerror += (W*x[i]-y[i])**2 # (입력가중치*x값(예측값) - y값(실제값))^2을 errorbyerror에 누적
  
  return errorbyerror/len(x) # errorbyerror에 list길이를 나눔


print("비용함수값은 ",cost_func(W, x, y), "입니다") # 비용함수값 출력


가중치를 입력하세요 4
비용함수값은  2.5 입니다


예시) x가 [1, 2] 이고 y가 [3, 6] 그리고 W가 4 일 경우  cost_func(W, x, y)함수의 리턴값은 2.5

### cost_func을 활용하여 웨이트(Weight)가 -5부터 5까지의 변화에 따른 코스트(cost)를 출력 해주세요.

In [104]:
# 여기 코드셀은 변경하지 마세요.
# 완성된 함수를 확인하는 과정으로 해당 코드셀을 실행해서 정상 출력되면 정답!
# 주의! 에러가 날 경우 데이터 코드셀과 cost function 코드셀을 실행했는지 확인해주세요.
for feed_W in range(-5, 6, 1):
  curr_cost = cost_func(feed_W, x, y)
  print("{:6.3f} | {:10.5f}".format(feed_W, curr_cost))

-5.000 |  160.00000
-4.000 |  122.50000
-3.000 |   90.00000
-2.000 |   62.50000
-1.000 |   40.00000
 0.000 |   22.50000
 1.000 |   10.00000
 2.000 |    2.50000
 3.000 |    0.00000
 4.000 |    2.50000
 5.000 |   10.00000


출력결과 : 정상